### PR TITLE
Adds `getOpenTerms` helper method

### PR DESCRIPTION
**Pull request by dantop114**
Solves  #12

### CODE REVIEW

**Review by sentilesdal — APPROVED** [review]
This looks great, thanks!

**Review by jrhea — CHANGES_REQUESTED** [review]
agreed with @sentilesdal here. the code is super clean. just needs to pass the lint step

**Comment by dantop114** [comment]
should be good now!

**Review by jrhea — APPROVED** [review]
lgtm

**Review by DannyDelott — APPROVED** [review]

**Pull request merged**
